server:
    port: 32764

spring:
    application:
        name: titan-gate-be-core
    profiles:
        active: local
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
        default-property-inclusion: ALWAYS

# JWT配置
jwt:
    secret: mySecretKey
    expiration: 86400  # 24小时

# OAuth2配置
oauth2:
    github:
        client-id: your-github-client-id
        client-secret: your-github-client-secret

# Dubbo配置
#dubbo:
#    application:
#        name: titan-gate-be-core
#    registry:
#        address: nacos://localhost:8848
#    protocol:
#        name: dubbo
#        port: 20880

mybatis:
    mapper-locations:
        - classpath:mappers/*.xml

logging:
    pattern:
        console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%thread]){faint} %clr(%-40.40logger{39}){cyan} %L %clr(:){faint} %m%n"
    level:
        root: INFO